clone:
  depth: full

pipelines:
  default:
    - step:
        name: Build on ubuntu bionic
        image: vvflow/env:build-ubuntu-bionic
        script:
          - pwd
          - ls -al
          - cmake ./
          - make -j
          - ctest -VV
          - cpack
        artifacts:
          - deb/vvflow-*.deb
    - step:
        name: Test on ubuntu bionic
        image: vvflow/env:test-ubuntu-bionic
        script:
          - ls -al
          - apt-get update
          - dpkg --force-depends -i deb/vvflow-*.deb
          - apt-get --fix-broken -y install
          - pytest ./pytest
